In [30]:
from PIL import Image
import pandas as pd
fileName=["pic1", "pic2", "pic3"]
prnData=[]

for fn in fileName:
    tmp=Image.open('./picture/'+fn+'.jpg')
    fName=fn+'.jpg'
    fm=tmp.format
    fw=tmp.width
    fh=tmp.height
    prnData.append([fName, fm, fw, fh])

    tmpRes=tmp.resize((300,300))
    tmpRes.save('./data/'+fn+"_300.jpg")    
    
for prn in prnData:
    print(f'파일명:{prn[0]},\t확장자:{prn[1]},\t너비:{prn[2]},\t높이:{prn[3]}')
    print("   ")

print("+=======================+")

df=pd.DataFrame(prnData, columns=["파일명", "확장자","너비","높이"])
df.to_csv('./파일정보.csv', encoding="cp949")
display(df)

파일명:pic1.jpg,	확장자:PNG,	너비:512,	높이:271

파일명:pic2.jpg,	확장자:JPEG,	너비:630,	높이:338

파일명:pic3.jpg,	확장자:JPEG,	너비:275,	높이:183

+=======================+

        파일명   확장자   너비   높이
0  pic1.jpg   PNG  512  271
1  pic2.jpg  JPEG  630  338
2  pic3.jpg  JPEG  275  183

In [62]:
from PIL import Image
import os
import pandas as pd

fileDir = './picture/'
fileName=os.listdir(fileDir)
prnData=[]

for fn in fileName:
    if(fn[-3:] == 'jpg'):
        tmp=Image.open(fileDir + fn)
        fm=tmp.format
        fw=tmp.width
        fh=tmp.height
        prnData.append([fName, fm, fw, fh])
        
        tmpRes=tmp.resize((300,300))
        tmpRes.save('./data/'+fn[:-4]+"_300.jpg")    
    
df=pd.DataFrame(prnData, columns=["파일명", "확장자","너비","높이"])
df.to_csv('./파일정보.csv', encoding="cp949")
#display(df)

print("+++++++++++++++++++++++++++++++++++")

fileDir_300 = './data/'
fileName_300=os.listdir(fileDir_300)
prnData_300=[]

for fn in fileName_300:
    if(fn[-3:] == 'jpg'):
        tmp=Image.open(fileDir_300 + fn)
        fm=tmp.format
        fw=tmp.width
        fh=tmp.height
        prnData_300.append([fn, fm, fw, fh])

        
df_300=pd.DataFrame(prnData_300, columns=["파일명", "확장자","너비","높이"])
df_300.to_csv('./리사이즈파일정보.csv', encoding="cp949")
display(df_300)

+++++++++++++++++++++++++++++++++++

              파일명   확장자   너비   높이
0   img10_300.jpg  JPEG  300  300
1   img11_300.jpg  JPEG  300  300
2   img12_300.jpg  JPEG  300  300
3   img13_300.jpg  JPEG  300  300
4   img14_300.jpg  JPEG  300  300
5   img15_300.jpg  JPEG  300  300
6   img16_300.jpg  JPEG  300  300
7   img17_300.jpg  JPEG  300  300
8   img18_300.jpg  JPEG  300  300
9   img19_300.jpg  JPEG  300  300
10   img1_300.jpg  JPEG  300  300
11  img20_300.jpg  JPEG  300  300
12  img21_300.jpg  JPEG  300  300
13  img22_300.jpg  JPEG  300  300
14  img23_300.jpg  JPEG  300  300
15  img24_300.jpg  JPEG  300  300
16  img25_300.jpg  JPEG  300  300
17  img26_300.jpg  JPEG  300  300
18  img27_300.jpg  JPEG  300  300
19  img28_300.jpg  JPEG  300  300
20  img29_300.jpg  JPEG  300  300
21   img2_300.jpg  JPEG  300  300
22  img30_300.jpg  JPEG  300  300
23   img3_300.jpg  JPEG  300  300
24   img4_300.jpg  JPEG  300  300
25   img5_300.jpg  JPEG  300  300
26   img6_300.jpg  JPEG  300  300
27   img7_300.jpg  JPEG  300  300
28   img8_300.jpg  JPEG  300  300
29   img9_300.jpg  JPEG  300  300
30   pic1_300.jpg  JPEG  300  300
31   pic2_300.jpg  JPEG  300  300
32   pic3_300.jpg  JPEG  300  300
33    pic_300.jpg  JPEG  300  300

In [8]:
txt='코로나19 탓에 손도 열심히 씻고, 마스크를 착용하고, 외출도 줄었다.'
lst=[]
tmp=""
count=0

for i in range(len(txt)):
    if txt[i] == " ":
        count += 1
        lst.append(tmp)
        tmp=""
    tmp = tmp + txt[i]
lst.append(tmp)

print(lst)
print("공백 수: ",count)

['코로나19', ' 탓에', ' 손도', ' 열심히', ' 씻고,', ' 마스크를', ' 착용하고,', ' 외출도', ' 줄었다.']
공백 수:  8